#!/bin/bash

set -euo pipefail

# Завершаем все старые eww бары
sudo killall -s SIGKILL eww || true

# Получаем список мониторов
monitors_json=$(hyprctl monitors -j)

# Проходим по каждому монитору
while read -r monitor; do
    mon_id=$(echo "$monitor" | jq -r '.id')
    mon_name=$(echo "$monitor" | jq -r '.name')
    mon_model=$(echo "$monitor" | jq -r '.model')
    model_short=$(echo "$mon_model" | awk '{$1=""; sub(/^ /,""); print}')

    backlight_match=""

    # Ищем backlight для монитора
    for dev in /sys/class/backlight/*; do
        [[ -d "$dev" ]] || continue
        udev_info=$(udevadm info --no-pager -a -p "$dev")

        if echo "$udev_info" | grep -qiE "$mon_name|$mon_model|$model_short"; then
            backlight_match=$(basename "$dev")
            break
        fi
    done

    # Получаем ширину монитора
    width=$(echo "$monitors_json" | jq -r ".[] | select(.id == $mon_id) | .width")

    # Запускаем eww бар для монитора
    eww open bar --id "$mon_id" --screen "$mon_id" \
        --arg MON_ID="$mon_id" --arg MON_W="$width" --arg BACKLIGHT="$backlight_match" \

done <<< "$(echo "$monitors_json" | jq -c '.[] | {id: .id, name: .name, model: .model}')"
