#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

# xsetroot -cursor_name left_ptr
# xset r rate 300 50

if [[ $(xrandr | grep "DP-2 connected") ]]; then
    bspc monitor DP-2 -d 1 2 3
    bspc monitor DP-0 -d 4
fi

if [[ $(xrandr | grep "eDP connected") ]]; then
    bspc monitor eDP -d 1 2 3 4
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^4'
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Exaile desktop='^2'
