#!/usr/bin/env bash

# Set environment variables
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Default 1 monitor with 6 workspaces
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

# bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc config window_gap                10
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        false
bspc config gapless_monocle           false

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc rule -a scratch sticky=on state=floating focus=on

bspc config border_width 0
bspc config top_padding 55
bspc config bottom_padding 1
bspc config left_padding 5
bspc config right_padding 5
bspc config normal_border_color "#C574DD"  
bspc config active_border_color "#5ADECD"
bspc config focused_border_color "#8897F4"
bspc config presel_feedback_color "#FF4971" 

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh


# # Set system vars for polybar
# "$HOME"/.config/bspwm/src/SetSysVars
#
# # Load current theme
# "${HOME}"/.config/bspwm/rices/"${RICETHEME}"/Theme.sh
#
# # Launch sxhkd daemon
# pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }
#
# # Launch picom
# pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom.conf & }

# Launch eww daemon
pidof -q eww || { eww -c "${HOME}"/.config/eww daemon & }

# # Launch clipboard daemon
# pidof -q greenclip || { greenclip daemon & }
#
# # Launch polkit
# pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }


# # Fix eww,  when entering fullscreen state
# bspc subscribe node_state | while read -r _ _ _ _ state flag; do
#     [[ "$state" == "fullscreen" ]] || continue
#         if [ "$flag" == on ]; then
#             ~/dotfiles/scripts/HideBar -h
#         else
#             ~/dotfiles/scripts/HideBar -u
#         fi
# done &
