#!/bin/bash

DIR="$HOME/.config/dunst/icons"
BRIGHTNESS_STEPS=7

function get_brightness {
  brightnessctl i | grep -oP '\(\K[^%\)]+'
}

function send_notification {
  icon="$DIR/brightness.svg"
  brightness=$(get_brightness)
  # Send the notification
  dunstify "Brightness $brightness%" -i $icon -t 1000 -r 5555 -u low -h int:value:$(($brightness))
}

case $1 in
  up)
    # increase the backlight by 5%
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%+" -q
    ;;
  down)
    # decrease the backlight by 5%
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%-" -q
    ;;
esac

send_notification
