#!/bin/bash

DIR="$HOME/.config/dunst/icons"

function get_volume() {
    wpctl get-volume @DEFAULT_SINK@ | awk '{print int($2 * 100) }'
}

function is_mute() {
    wpctl get-volume @DEFAULT_SINK@ | grep "[MUTED]"
}

function send_notification() {
    if is_mute; then
        icon_name="$DIR/notification-audio-volume-muted.svg"
        dunstify "                  Muted" -i $icon_name -a "VolBar" -t 500 -r 5555 -u low -h string:synchronous:audio-volume
    # fi
    else
        volume=$(get_volume)
        if [ "$volume" = "0" ]; then
        icon_name="$DIR/notification-audio-volume-muted.svg"
        elif [ "$volume" -lt "30" ]; then
            icon_name="$DIR/notification-audio-volume-low.svg"
        elif [ "$volume" -lt "70" ]; then
            icon_name="$DIR/notification-audio-volume-medium.svg"
        else
            icon_name="$DIR/notification-audio-volume-high.svg"
        fi
        dunstify "                    $volume%" -i $icon_name -a "VolBar" -t 1000 -r 5555 -u low -h int:value:$(($volume))
    fi
}

case $1 in
    up)
        # Unmute
        wpctl set-mute @DEFAULT_SINK@ 0

        wpctl set-volume @DEFAULT_SINK@ 5%+ -l 1
        ;;
    down)
        # Unmute
        wpctl set-mute @DEFAULT_SINK@ 0

        wpctl set-volume @DEFAULT_SINK@ 5%- -l 1
        ;;
    mute)
        wpctl set-mute @DEFAULT_SINK@ toggle
        ;;
esac
send_notification
